### ISSUE TITLE
Cross version testing

### ISSUE THREAD

**Issue by britter** [gradlex-org/build-parameters#17]
We currently only test against the Gradle version that's running the build. We should extend our testing to cover more Gradle versions, also to explore what the minimal Gradle version is that we support.

**Comment by lacasseio** [comment]
Cross-version testing is solved with [my toolbox plugins](https://github.com/gradle-plugins/toolbox). See https://docs.nokee.dev/samples/gradle-plugin-development-with-testing-strategies/.
