### ISSUE TITLE
Fail the build when it's running on an unsupported Gradle version

### ISSUE THREAD

**Issue by britter** [gradlex-org/build-parameters#18]
Requires #17

When the plugin is applied to a build that's running with a Gradle version that's known to be not compatible the plugin should log a warning or even fail the build.

**Comment by lacasseio** [comment]
There is some overlap with my toolbox plugins to improve plugin development: https://github.com/gradle-plugins/toolbox/issues/9. We should talk about that. I don't see this issue as specific to this plugin but as a more general improvement to Gradle plugin development.
