### ISSUE TITLE
Reading from .properties files?

### ISSUE THREAD

**Issue by ankushg** [gradlex-org/build-parameters#21]
Any chance of adding support for reading parameter values from `local.properties` or `gradle.properties` files too?

Not sure how idiomatic it is, but I've seen a few projects that use those areas to store things that I would consider to be build parameters :)

**Comment by britter** [comment]
Hey @ankushg, `gradle.properties` will already work. Would that already be enough to support the use case you're thinking about?

**Comment by ankushg** [comment]
Oh that's great, I must have missed that in the docs

I still think reading from `local.properties` would also be a good addition -- plenty of folks use those files to avoid checking in secrets to version control: https://blog.mindorks.com/using-local-properties-file-to-avoid-api-keys-check-in-into-version-control-system

**Comment by jjohannes** [comment]
*Team Decision*

Useful feature to separate built-in Gradle properties (like `org.gradle.caching`), which belong into a checked-in `gradle.properties`, from **build parameters**.

Should not be fixed to one properties file like `local.properties` but work for arbitrarily named property files.

Details about DSL/API and override rules need to be worked out.

**Comment by saket** [comment]
+1 to this. My `gradle.properties` is checked into git, but `secrets.properties` and `local.properties` are not.

**Comment by thecodesmith** [comment]
For consideration, we use https://github.com/stevesaliman/gradle-properties-plugin to load properties from `gradle-[env].properties` to override parameters depending on the environment (mainly `ci` and `local`). I'm working to incorporate this plugin and just ran into this issue, still working out how to solve it. Might be useful to consider the override rules used by `gradle-properties-plugin` in case the two plugins can coexist.

**Comment by thecodesmith** [comment]
Some relevant details on the [gradle-properties-plugin](https://github.com/stevesaliman/gradle-properties-plugin) I mentioned earlier, regarding the issues that plugin has with Configuration Cache and why it is likely incompatible with this plugin: https://github.com/stevesaliman/gradle-properties-plugin/issues/39#issuecomment-1027532152.

I am happy to contribute if the team has some guidance on how this should be implemented.

**Comment by britter** [comment]
This plugin is about modeling parameters that are passed via the command line with `-P`, not to model everything you put into `gradle.properties` or other properties files. For that reason we consider this out of scope.
