### ISSUE TITLE
Generate Settings Plugin

### ISSUE THREAD

**Issue by jjohannes** [gradlex-org/build-parameters#24]
Next to the "Project Plugin" that applies the generated Extension to a project (build file) we should also generate a "Settings Plugin" that can be applied in the settings file to access build parameters there. An example is this from the plugins very own build:

```
if ("CI" in System.getenv()) {
    gradleEnterprise {
        buildScan {
            publishAlways()
            termsOfServiceUrl = "https://gradle.com/terms-of-service"
            termsOfServiceAgree = "yes"
        }
    }
}
```

**Comment by britter** [comment]
I think the challenge here is that we don't have access to the project object in a settings plugin so I don't know how we can get a `ProviderFactory` instance that we can use to access `gradleProperty` and `environmentVariable` methods. Or am I missing something?

**Comment by jjohannes** [comment]
```
    @Inject
    public abstract ProviderFactory getProviders();
```

should do it.
