### ISSUE TITLE
Check that only valid build parameters are passed via -P (and not -D)

### ISSUE THREAD

**Issue by lacasseio** [gradlex-org/build-parameters#28]
This is a common gotcha where some users source properties from Gradle, some source them from System. Preferring only one will guarantee to leave some users behind or scratching their heads into why their properties were not considered. Or worst, it will be a silent error (i.e. `property.getOrNull()`) The suggestion is always to follow the general Gradle precedence ordering: https://docs.gradle.org/current/userguide/build_environment.html#header

If sourcing from both property types is not wanted, give a guiding error message (even if there is a default value, which would mostly be a warning message), aka "you are requesting Gradle property 'foo' but a System property 'foo' was found, don't do that". The solution can be either in the plugin or in Gradle itself. Already requested that feature long ago; maybe you will have better luck making things move.

**Comment by britter** [comment]
Hey @lacasseio can you give a concrete example of when you would use a system property to inject a build parameter instead of a Gradle property? It's not clear to me why you would do this.

**Comment by lacasseio** [comment]
It's more a matter of least surprised for the user. Some users may be converting from `System.getProperty` because that is what they were using before and then forget to change the CI command line from -D to -P. Without any warning or support, users will most certainly be in the unknown.

Gradle build parameters already support both Gradle property and System property for most of them.

It's really a matter of making it simple for the users so it just works.

**Comment by britter** [comment]
> Gradle build parameters already support both Gradle property and System property for most of them.

I don't understand this part. What exactly are you referring to with "Gradle build parameters"? Are you talking about the `project.properties` / `providers.gradlePropery` APIs?

If you put `systemProp.someThing` into your `gradle.properties` you can read that value using `providers.gradleProperty` or `project.properties`. You will have to use `System.getProperty`.

So I still don't understand what the use case for a system property override would be 🙃

**Comment by jjohannes** [comment]
How I understand this, it's mainly about the command line -P vs -D. Which I agree is confusing.

But because it is a different kind of notation inside the  gradle.properties file, I would tend towards adding a warning. Instead of handling -D and -P the same.

I am not sure. But we should consider doing something here.

**Comment by britter** [comment]
If we're going to do something here, it's just going to be a warning if we find a system property of the same name as a Gradle property.

**Comment by jjohannes** [comment]
Version `1.4` will now fail if you define something via `-D` that is a defined build parameter. For additional feature ideas / improvements new issues should be opened.
