### ISSUE TITLE
Incompatibility with Android projects

### ISSUE THREAD

**Issue by saket** [gradlex-org/build-parameters#31]
👋 I'm trying to add `build-parameters` but it seems to be incompatible with Android projects. Can the `java` plugin be avoided?

```bash
A problem occurred configuring project ':backend'.
> com.android.build.gradle.internal.BadPluginException: The 'java' plugin has been applied, but it is not compatible with the Android plugins.
```

**Comment by jjohannes** [comment]
Hi @saket 👋 . This plugin is special in the regard that the actual plugin you are using in the end is generated. In your build files, you have to apply the plugin `id("build-parameters")` (the generated one).

The plugin `id("org.gradlex.build-parameters)` needs to be applied, and configured, in a build file of your _convention plugins_ build (aka  `gradle/plugins` / `build-logic` / `buildSrc`). If you do not have such a build yet, you need to add it. Ideally via adding this to the settings file:

```
plugins {
  includeBuild("gradle/plugins")
}
```

It's generally a good way to organise build configuration.

See also documentation: https://gradlex.org/build-parameters/#setup
And example: https://github.com/gradlex-org/build-parameters/tree/main/samples/basics

**Comment by britter** [comment]
Closing as not being an issue.

**Comment by saket** [comment]
Oh whoops I completely misread the primer section. I was able to add `build-parameters` by reading the Usage section. Thank you!
