### ISSUE TITLE
Enum Build Parameters: Support values that are not valid Java names

### ISSUE THREAD

**Issue by jjohannes** [gradlex-org/build-parameters#64]
Automatically detect this and convert them to a name that is supported in the generated code:

- Names that contain `-` 
  - convert `-` to `_` 
  - example `my-value` -> `my_value`
- Names that are Java keywords
  - prepend a `_` (?)
  - for example `int` -> `_int`

Use case: You may have existing parameters already. Values are then often dictated by existing systems/setups in a company and you can't pick them freely (for example branch names in a git-flow like process). It would be nice if the plugin could still support such parameters as Enums. The current solution is to use a `string(...)` parameter instead.

**Comment by britter** [comment]
Hey @jjohannes, can you please extend this with a more comprehensive example?

* What's the value you're passing to the build, e.g. how that the portion of the command line look like?
* How would you like to define the enum parameter?
* How would you like to use the generated code in your build script?

The way I see it if we implement this you would have to know about the implicit mapping in order to be able to use the generated code in your build script:

```shell
./gradlew build -Pmy-value
```

```kotlin
// build.gradle.kts
if (buildParameters.myEnum == MyEnum.my_value) { // you need to know this
   // ...
}
```

So I wonder if it would be better to valide all parameter names and enum parameter values for being valid java identifiers and then provide a way for enums to override how we map from the parameter supplied to the build to the enum value.

**Comment by jjohannes** [comment]
There might also be other options to consider to support the use case. Let's try again. 😄 

## Use Case

I have an existing environment with some configuration I want to pass into the build. A concrete example is that I use a git-flow process, I am on a feature branch and want to let the build know from which `baseBranch` I forked the feature branch. The possible base branches are:

- `main`
- `int` 
- `fix-rc`

These names already exist and other tools rely on them. So the names themselves can't be changed and I also want to use them for `-PbaseBranch=int` so that **build users** do not have to know that the names are slightly different in Gradle.

In the DSL I would like to write

```
buildParameter {
   enumeration("baseBranch") {
       description.set("...")
       values.addAll("main", "int", "fix-rc")
       defaultValue.set("main")
  }
}
```
## Possible Solutions

Solutions that came to my mind:

1. Allow more names, but automatically change them in the enum so that they work (as suggested in the original description)
2. Add a configuration option like `javaName = "..."` to the enum param DSL, so that the mapping of names is explicit. (This would unfortunately blow up the DSL here, as currently the names are just strings. 🤔)
3. Leave enums as they are, but allow string parameters to have a limited set of values as well. So in the generated code everything is a String (so basically any value is allowed from Java's perspective) but the plugin still checks if the parameter has one of the allowed values.

What put me off initially when I tried this, is that Java limits which names I can use. Which I don't like. As a **build user** I don't care how the values are represented internally in the build. I never look at the generated code. Ideally, we would add #7 so that build users don't need to look at he build at all. But if they check, they should check the place where the parameters are defined with this plugin's DSL and not the generated code.

**Solution 1:** I agree, that for the **build author** it is not ideal if the name of the param is different than the enum value. But I think that small changes alike adding/replacing `_` is something that's quite obvious. The code generation for the version catalog does something similar (replacing `-` with `.` if IIRC). So I think it would be okay, but I see your point that it's not ideal. (In any case, the **build user**, would not need to know about these internals.)

**Solution 2:** Would solve the issue that the mapping is implicit. The **build author** can control and look up the mapping through the DSL. What I don't like is that the **build author** needs to do define more and blow up the parameter description, just because of Java limitations (implementation details). 

**Solution 3:** I don't really like it, because conceptually then String and Enum are sometimes the same from a **build user** perspective.

**Comment by jjohannes** [comment]
We go with the **Solution 1** outlined above.
