### ISSUE TITLE
Repository credentials produce "Unknown build parameter" error

### ISSUE THREAD

**Issue by LarsKaulen** [gradlex-org/build-parameters#92]
Starting with version 1.4 unrecognized parameters lead to an exception (see #28).

When using the [gradle repository credentials feature](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials), locally I enter the username and password (let's say they are called `nexusUsername` and `nexusPassword` as my repository is called `nexus`) in my `~/gradle.properties` and everything works fine.

But when running on CI (gitlab in my case), I have the credentials of a technical user as secret CI/CD variables and pass them via `-PnexusUsername=$TECHNICAL_USER_NAME -PnexusPassword=$TECHNICAL_USER_PASSWORD` to gradle.
Then I receive the following exception: `Unknown build parameter: nexusPassword`

What would be your advice to handle this situation?

**Comment by jjohannes** [comment]
This is the new _parameter validation_ feature. To get the old behavior, you can turn it off as described here:
https://gradlex.org/build-parameters/#disable-build-parameter-validation

The feature checks that what you pass with `-P` is actually declared as _build parameter_ (e.g. to catch typos when you use this as user on the command line). So if you do not want to turn it off, you should:

- Declare `nexusUsername` and `nexusPassword` as build parameters (even if you never access them through the generated extension).
- You may also consider accessing the parameters through the extension to get the user/passwords and pass them to Gradle (similar to what is done in the example in the [primer](https://gradlex.org/build-parameters/#primer)). Then you can directly couple them to the EVV variables you use on CI and do not need a special Gradle command line there: https://gradlex.org/build-parameters/#deriving-parameter-values-from-environment-variables (this is what I would do)

**Comment by LarsKaulen** [comment]
Thanks for the detailed answer, which helped me resolve the problem.
For now I went with disabling the validation, but I will certainly keep the second option in mind.
